name: 'Deploy to Rezoleo via SFTP'
description: 'Déploie le contenu du repo sur Hippolyte via SFTP avec lftp + user/password, en ignorant .git/ et en respectant partiellement le .gitignore'
inputs:
  sftp-password:
    description: 'Mot de passe pour le serveur SFTP'
    required: true
  sftp-user:
    description: 'Nom d’utilisateur pour le serveur SFTP'
    required: true

runs:
  using: "composite"
  steps:
    - name: Installer lftp
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: lftp
        version: 1.0

    - name: Déployer via lftp
      env:
        SFTP_USER: ${{ inputs.sftp-user }}
        SFTP_PASSWORD: ${{ inputs.sftp-password }}
      run: |
        lftp -p 8888 "sftp://$SFTP_USER:$SFTP_PASSWORD@sftp.rezoleo.fr" -e "set sftp:auto-confirm yes; mirror -e -R -x .git --exclude-glob-from=.gitignore ./ ./writable ; quit"
      shell: bash
